style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/montanaflynn/stats
options:
  commits:
    filters:
      Type:
        - Add
        - Fix
        - Update
        - Remove
        - feat
        - fix
        - chore
        - ci
  commit_groups:
    sort_by: Custom
    title_maps:
      feat: Add
      fix: Fix
      chore: Chore
      ci: CI
    title_order:
      - feat
      - fix
      - ci
      - chore
  header:
    pattern: "^(\\w+)(?:\\(.*\\))?!?:?\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
